07-05 10:18:01 jdbc[2]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-169]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.dubture.symfony.index.SymfonyDbFactory.<init>(SymfonyDbFactory.java:103)
	at com.dubture.symfony.index.SymfonyDbFactory.getInstance(SymfonyDbFactory.java:58)
	at com.dubture.symfony.index.SymfonyIndexer.<init>(SymfonyIndexer.java:51)
	at com.dubture.symfony.index.SymfonyIndexer.getInstance(SymfonyIndexer.java:61)
	at com.dubture.symfony.core.SymfonyCorePlugin$1.resourceChanged(SymfonyCorePlugin.java:46)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:139)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 25 more
